version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  test:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.comatch.com/en/,https://deutsche-bank.de/,https://developers.google.com/web/tools/lighthouse,https://www.linkedin.com,https://github.com/

workflows:
  test:
    jobs:
      - test
